package com.wallet.secure.wallet.dto;

import com.wallet.secure.common.enums.CurrencyCode;
import jakarta.validation.constraints.NotNull;
import lombok.Getter;

/**
 * DTO for POST /wallets
 * Creates a new wallet for the authentication user
 * Why only currency and nothing else:
 * - user_id -> comes from JWT (@AuthenticationPrincipal), never from body
 * - balance -> always starts at 0, client cannot set initial balance
 * - status -> always ACTIVE on creation, client cannot set status
 * - id -> generated by DB
 * OWASP A01: mass assignment prevention - client only chooses the currency
 * Everything else is controlled server-side
 */
@Getter
public class CreateWalletRequest {

    /**
     * Currency fot the new wallet
     * @NotNull: rejects null - must send a valid CurrencyCode value
     * Invalid values (ex: "BITCOIN") -> 400 before reaching WalletService
     * Supported: USD, EUR, COP, MXN, ARS
     */
    @NotNull(message = "Currency is required")
    private CurrencyCode currency;
}