package com.wallet.secure.auth.service;

import com.wallet.secure.auth.dto.SessionResponse;
import com.wallet.secure.auth.entity.Session;
import com.wallet.secure.auth.repository.SessionRepository;
import com.wallet.secure.auth.security.JwtService;
import com.wallet.secure.common.exception.InvalidCredentialsException;
import com.wallet.secure.common.exception.ResourceNotFoundException;
import com.wallet.secure.common.response.ApiResponse;
import com.wallet.secure.user.entity.User;
import lombok.RequiredArgsConstructor;
import lombok.extern.log4j.Log4j2;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.time.Instant;
import java.util.HexFormat;
import java.util.List;
import java.util.UUID;

/**
 * Manages the full lifecycle of user sessions in user_sessions table.
 *
 * RESPONSIBILITIES:
 * 1. createSession()          → called by AuthService on login/register
 * 2. validateSession()        → called by AuthService on refresh
 * 3. revokeSession()          → called by AuthService on logout (single device)
 * 4. revokeAllSessions()      → called on password change or admin suspension
 * 5. getActiveSessions()      → called by SessionController (user sees their devices)
 * 6. revokeSpecificSession()  → called when user logs out from one device
 *
 * KEY SECURITY DESIGN — token_hash:
 * We NEVER store the raw refresh token in the DB.
 * We store SHA-256(refreshToken) — a one-way hash.
 *
 * Flow on login:
 *   refreshToken = jwtService.generateRefreshToken(email)  ← random JWT
 *   tokenHash    = sha256(refreshToken)                    ← stored in DB
 *   client receives refreshToken                           ← never stored raw
 *
 * Flow on refresh:
 *   client sends refreshToken
 *   server computes sha256(refreshToken)
 *   server looks up user_sessions WHERE token_hash = sha256(refreshToken)
 *   if found AND not revoked AND not expired → valid ✅
 *
 * WHY SHA-256 and not BCrypt for token hashing:
 * BCrypt is slow by design (for passwords — prevents brute force).
 * Tokens are long random strings (256+ bits) — brute force is impossible.
 * SHA-256 is fast and deterministic → lookups are instant.
 * OWASP A02: right algorithm for the right use case.
 *
 * OWASP A07: every session is server-tracked — real revocation capability.
 */
@Service
@RequiredArgsConstructor
@Log4j2
public class SessionService {

    private final SessionRepository sessionRepository;
    private final JwtService jwtService;

    // ─── Session Creation

    /**
     * Creates a new session entry when a user logs in or registers.
     * Called by AuthService.generateAndSaveTokens() — every new token = new session.
     *
     * @param user         the authenticated user
     * @param refreshToken the raw refresh token just generated by JwtService
     * @param ipAddress    client IP from HttpServletRequest
     * @param userAgent    browser/device string from User-Agent header
     */
    @Transactional
    public Session createSession(User user, String refreshToken,
                                 String ipAddress, String userAgent) {

        String tokenHash = hashToken(refreshToken);
        Instant expiresAt = Instant.now().plusMillis(jwtService.getRefreshExpirationMs());

        Session session = Session.builder()
                .user(user)
                .tokenHash(tokenHash)
                .ipAddress(ipAddress)
                .userAgent(userAgent)
                .expiresAt(expiresAt)
                .build();

        Session saved = sessionRepository.save(session);

        log.info("Session created: sessionId={} userId={} ip={}",
                saved.getId(), user.getId(), ipAddress);

        return saved;
    }

    // ─── Session Validation

    /**
     * Validates that a refresh token has an active session in the DB.
     * Called by AuthService.refresh() before issuing a new access token.
     *
     * Checks performed (in order):
     * 1. Session exists in DB (token was legitimately issued)
     * 2. Session is not revoked (user hasn't logged out)
     * 3. Session has not expired (expiresAt > now)
     *
     * WHY check DB even though JWT signature is already valid:
     * A valid JWT signature only proves the token was issued by us.
     * It does NOT prove the user hasn't logged out since.
     * DB check = real revocation enforcement.
     * OWASP A07: stateful validation closes the logout gap.
     *
     * @param refreshToken the raw refresh token from the client request
     * @return the valid Session entity
     * @throws InvalidCredentialsException if session not found, revoked, or expired
     */
    @Transactional(readOnly = true)
    public Session validateSession(String refreshToken) {

        String tokenHash = hashToken(refreshToken);

        Session session = sessionRepository.findByTokenHash(tokenHash)
                .orElseThrow(() -> {
                    log.warn("Session not found for token hash — possible token reuse after logout");
                    return new InvalidCredentialsException("Session not found or already revoked");
                });

        if (!session.isActive()) {
            log.warn("Inactive session used: sessionId={} revoked={} expiresAt={}",
                    session.getId(), session.isRevoked(), session.getExpiresAt());
            throw new InvalidCredentialsException("Session has been revoked or expired");
        }

        return session;
    }

    // ─── Session Revocation

    /**
     * Revokes a specific session by its token hash.
     * Called by AuthService.logout() — single device logout.
     *
     * The user remains logged in on other devices.
     * Only the session matching this refresh token is revoked.
     *
     * @param refreshToken the raw refresh token being revoked
     */
    @Transactional
    public void revokeByToken(String refreshToken) {

        String tokenHash = hashToken(refreshToken);

        sessionRepository.findByTokenHash(tokenHash).ifPresentOrElse(
                session -> {
                    session.revokeNow();
                    sessionRepository.save(session);
                    log.info("Session revoked: sessionId={} userId={}",
                            session.getId(), session.getUser().getId());
                },
                () -> log.warn("Attempted to revoke non-existent session — token may have already expired")
        );
    }

    /**
     * Revokes ALL active sessions for a user — all devices.
     * Called on:
     * → Password change — security best practice (OWASP A07)
     * → Admin account suspension — immediate access termination
     * → User self-service "logout from all devices"
     *
     * Uses a single bulk UPDATE — efficient regardless of session count.
     *
     * @param userId the user whose sessions are all being terminated
     */
    @Transactional
    public void revokeAllSessions(UUID userId) {

        sessionRepository.revokeAllActiveSessionsForUser(userId, Instant.now());
        log.info("All sessions revoked for userId={}", userId);
    }

    /**
     * Revokes a specific session by its UUID.
     * Called by SessionController DELETE /sessions/{sessionId}.
     * The requesting user can only revoke their OWN sessions.
     *
     * @param sessionId UUID of the session to revoke
     * @param userId    ID of the requesting user — ownership check
     * @throws ResourceNotFoundException   if session doesn't exist
     * @throws InvalidCredentialsException if session belongs to another user
     */
    @Transactional
    public ApiResponse<Void> revokeSessionById(UUID sessionId, UUID userId) {

        Session session = sessionRepository.findById(sessionId)
                .orElseThrow(() -> new ResourceNotFoundException("Session not found"));

        // OWASP A01: user can only revoke their own sessions
        if (!session.getUser().getId().equals(userId)) {
            log.warn("Unauthorized session revocation attempt: requesterId={} sessionOwnerId={}",
                    userId, session.getUser().getId());
            throw new InvalidCredentialsException("Not authorized to revoke this session");
        }

        if (session.isRevoked()) {
            return ApiResponse.ok("Session was already revoked", null);
        }

        session.revokeNow();
        sessionRepository.save(session);

        log.info("Session revoked by user: sessionId={} userId={}", sessionId, userId);
        return ApiResponse.ok("Session revoked successfully", null);
    }

    // ─── Session Read

    /**
     * Returns all active sessions for a user with the current session flagged.
     * Called by SessionController GET /sessions.
     *
     * The currentRefreshToken parameter is used to determine which session
     * in the list corresponds to the current device — flagged as current=true.
     *
     * @param userId               the authenticated user's ID
     * @param currentRefreshToken  the refresh token from the current request
     *                             (null if not available)
     * @return list of active sessions with current session flagged
     */
    @Transactional(readOnly = true)
    public ApiResponse<List<SessionResponse>> getActiveSessions(UUID userId,
                                                                String currentRefreshToken) {

        String currentHash = currentRefreshToken != null
                ? hashToken(currentRefreshToken) : null;

        List<SessionResponse> sessions = sessionRepository
                .findActiveSessionsByUserId(userId, Instant.now())
                .stream()
                .map(s -> SessionResponse.fromEntity(s,
                        currentHash != null && currentHash.equals(s.getTokenHash())))
                .toList();

        return ApiResponse.ok("Active sessions retrieved", sessions);
    }

    /**
     * Returns ALL sessions (active + revoked + expired) for a user.
     * ADMIN only — called by SessionController GET /sessions/users/{userId}.
     * Used for forensic investigation: "show me the full session history"
     *
     * @param userId the target user's ID
     */
    @Transactional(readOnly = true)
    public ApiResponse<List<SessionResponse>> getAllSessionsForUser(UUID userId) {

        List<SessionResponse> sessions = sessionRepository
                .findByUserIdOrderByCreatedAtDesc(userId)
                .stream()
                .map(SessionResponse::fromEntity)
                .toList();

        return ApiResponse.ok("All sessions retrieved", sessions);
    }

    // ─── Token Hashing

    /**
     * Computes SHA-256 hash of a refresh token for secure DB storage.
     *
     * WHY SHA-256 and not BCrypt:
     * BCrypt is intentionally slow (for password hashing — prevents brute force).
     * Refresh tokens are long random strings (256+ bits entropy).
     * Brute forcing a 256-bit random token is computationally impossible.
     * SHA-256 is fast, deterministic, and perfect for token lookup by hash.
     *
     * WHY HexFormat (Java 17+) and not Base64:
     * Hex output is URL-safe and human-readable in DB queries.
     * 64-char hex string is more readable than Base64 for debugging.
     * Both are secure — this is a style choice.
     *
     * OWASP A02: raw tokens never touch the DB — only their hashes.
     *
     * @param token the raw JWT refresh token
     * @return lowercase hex SHA-256 hash (64 characters)
     */
    public String hashToken(String token) {
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            byte[] hashBytes = digest.digest(token.getBytes(StandardCharsets.UTF_8));
            return HexFormat.of().formatHex(hashBytes);
        } catch (NoSuchAlgorithmException e) {
            // SHA-256 is guaranteed to be available in all JVMs (Java SE spec)
            // This catch is required by the compiler but will never execute
            throw new IllegalStateException("SHA-256 algorithm not available", e);
        }
    }
}